### ISSUE TITLE
Shorten download fail traceback

### ISSUE THREAD

**Issue by ResidentMario** [Kaggle/kaggle-api#11]
Currently executing a request for a dataset which the CLI (in this case, because I'm mis-specifying a parameter) can't find results in an obnoxiously long traceback:

```
No datasets found
(kaggle-datasets-workflow) Alexs-MacBook:kaggle-datasets-workflow alex$ kaggle datasets download -d zillow/zecon -f ~/Desktop/kaggle-datasets-workflow
Traceback (most recent call last):
  File "/Users/alex/miniconda3/envs/kaggle-datasets-workflow/bin/kaggle", line 11, in <module>
    sys.exit(main())
  File "/Users/alex/miniconda3/envs/kaggle-datasets-workflow/lib/python3.6/site-packages/kaggle/cli.py", line 18, in main
    out = args.func(**command_args)
  File "/Users/alex/miniconda3/envs/kaggle-datasets-workflow/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 191, in datasetDownloadCli
    self.datasetDownloadFile(dataset, file, path, force, quiet)
  File "/Users/alex/miniconda3/envs/kaggle-datasets-workflow/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 165, in datasetDownloadFile
    response = self.datasets_download_file(owner_slug = ownerSlug, dataset_slug = datasetSlug, file_name = file, _preload_content = False)
  File "/Users/alex/miniconda3/envs/kaggle-datasets-workflow/lib/python3.6/site-packages/kaggle/api/kaggle_api.py", line 780, in datasets_download_file
    (data) = self.datasets_download_file_with_http_info(owner_slug, dataset_slug, file_name, **kwargs)  # noqa: E501
  File "/Users/alex/miniconda3/envs/kaggle-datasets-workflow/lib/python3.6/site-packages/kaggle/api/kaggle_api.py", line 870, in datasets_download_file_with_http_info
    collection_formats=collection_formats)
  File "/Users/alex/miniconda3/envs/kaggle-datasets-workflow/lib/python3.6/site-packages/kaggle/api_client.py", line 318, in call_api
    _preload_content, _request_timeout)
  File "/Users/alex/miniconda3/envs/kaggle-datasets-workflow/lib/python3.6/site-packages/kaggle/api_client.py", line 149, in __call_api
    _request_timeout=_request_timeout)
  File "/Users/alex/miniconda3/envs/kaggle-datasets-workflow/lib/python3.6/site-packages/kaggle/api_client.py", line 339, in request
    headers=headers)
  File "/Users/alex/miniconda3/envs/kaggle-datasets-workflow/lib/python3.6/site-packages/kaggle/rest.py", line 235, in GET
    query_params=query_params)
  File "/Users/alex/miniconda3/envs/kaggle-datasets-workflow/lib/python3.6/site-packages/kaggle/rest.py", line 225, in request
    raise ApiException(http_resp=r)
kaggle.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'private', 'Content-Length': '8428', 'Content-Type': 'text/html; charset=utf-8', 'Set-Cookie': '__RequestVerificationToken=ymVDVMYDh8rl7KZtsuVVE99rbnMnM0GXH9GtqQT4IMkjo9ojIr89hxXnNclp_PuYZ1GqxH9zloXgsN0RLa3goyV2wqo1; path=/; secure; HttpOnly, TempData=_K/uVcKCvMS1hOM+yULAgi42jyWu2hJNqCdx3I/QOS5NSAjtsc5xphISiR6NrYmBl8RWIlxlpLPLFd0wZKsstUfsau//nIhg4GnlE9R0EaFpySgH1p7rkVhNVPaEoDmzNo11OA0g1YsOlzhWlyhhzxJcFfIrHlYUVVJZSp8jbkgq00H7E4Wxxs8YbMhP9UQboyRej/KhGUTJGlv8kczTrBdjUOFU=; path=/; secure; HttpOnly, ARRAffinity=768ad72a3486513268ab2bd5b8de0721019eb85ba61510084adaafb0fb5fb390;Path=/;HttpOnly;Domain=www.kaggle.com', 'X-Frame-Options': 'SAMEORIGIN', 'Date': 'Thu, 08 Mar 2018 20:16:37 GMT'})
HTTP response body: b'<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>Kaggle: Your Home for Data Science</title>\r\n    <meta charset="utf-8" />\r\n    <meta name="robots" content="index, follow"/>\r\n    <meta name="theme-color" content="#008ABC" />\r\n    <link rel="dns-prefetch" href="https://www.google-analytics.com" /><link rel="dns-prefetch" href="https://stats.g.doubleclick.net" /><link rel="dns-prefetch" href="https://js.intercomcdn.com" /><link rel="preload" href="https://az416426.vo.msecnd.net/scripts/a/ai.0.js" as=script /><link rel="dns-prefetch" href="https://kaggle2.blob.core.windows.net" />\r\n    <link href="/content/v/d420a040e581/kaggle/favicon.ico" rel="shortcut icon" type="image/x-icon" />\r\n    <link rel="manifest" href="/static/json/manifest.json">\r\n    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic" rel=\'stylesheet\' type=\'text/css\'>\r\n                    <link rel="stylesheet" type="text/css" href="/static/assets/vendor.css?v=72f4ef2ebe4f"/>\r\n        <link rel="stylesheet" type="text/css" href="/static/assets/app.css?v=9fc7920d2526"/>\r\n        <script>\r\n            \r\n            (function () {\r\n                var originalError = window.onerror;\r\n\r\n                window.onerror = function (message, url, lineNumber, columnNumber, error) {\r\n                    var handled = originalError && originalError(message, url, lineNumber, columnNumber, error);\r\n                    var blockedByCors = message && message.toLowerCase().indexOf("script error") >= 0;\r\n                    return handled || blockedByCors;\r\n                };\r\n            })();\r\n        </script>\r\n    <script>\r\n        var appInsights=window.appInsights||function(config){\r\n        function i(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s="AuthenticatedUserContext",h="start",c="stop",l="Track",a=l+"Event",v=l+"Page",y=u.createElement(o),r,f;y.src=config.url||"https://az416426.vo.msecnd.net/scripts/a/ai.0.js";u.getElementsByTagName(o)[0].parentNode.appendChild(y);try{t.cookie=u.cookie}catch(p){}for(t.queue=[],t.version="1.0",r=["Event","Exception","Metric","PageView","Trace","Dependency"];r.length;)i("track"+r.pop());return i("set"+s),i("clear"+s),i(h+a),i(c+a),i(h+v),i(c+v),i("flush"),config.disableExceptionTracking||(r="onerror",i("_"+r),f=e[r],e[r]=function(config,i,u,e,o){var s=f&&f(config,i,u,e,o);return s!==!0&&t["_"+r](config,i,u,e,o),s}),t\r\n        }({\r\n            instrumentationKey:"5b3d6014-f021-4304-8366-3cf961d5b90f",\r\n            disableAjaxTracking: true\r\n        });\r\n        window.appInsights=appInsights;\r\n        appInsights.trackPageView();\r\n    </script>\r\n    \r\n    \r\n    \r\n \r\n    \r\n    <script>\r\n    window.ga = window.ga || function () { (ga.q = ga.q || []).push(arguments) }; ga.l = +new Date;\r\n    ga(\'create\', \'UA-12629138-1\', \'auto\');\r\n    ga(\'set\', \'displayFeaturesTask\', null);\r\n    ga(\'send\', \'pageview\');\r\n    </script>\r\n    <script async src="https://www.google-analytics.com/analytics.js"></script>\r\n\r\n    \r\n<script>\r\n    !function(f,b,e,v,n,t,s)\r\n    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?\r\n            n.callMethod.apply(n,arguments):n.queue.push(arguments)};\r\n        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version=\'2.0\';\r\n        n.queue=[];t=b.createElement(e);t.async=!0;\r\n        t.src=v;s=b.getElementsByTagName(e)[0];\r\n        s.parentNode.insertBefore(t,s)}(window,document,\'script\',\r\n        \'https://connect.facebook.net/en_US/fbevents.js\');\r\n    fbq("set", "autoConfig", "false", "136809193586742");\r\n    fbq(\'init\', \'136809193586742\'); \r\n    fbq(\'track\', \'PageView\');\r\n</script>\r\n<noscript>\r\n    <img height="1" width="1" src="https://www.facebook.com/tr?id=136809193586742&ev=PageView&noscript=1"/>\r\n</noscript>\r\n\r\n    \r\n\r\n    <script>\r\n          window.intercomSettings = {\r\n            app_id: "koj6gxx6"\r\n          };\r\n    </script>\r\n<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic(\'reattach_activator\');ic(\'update\',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement(\'script\');s.type=\'text/javascript\';s.async=true;s.src=\'https://widget.intercom.io/widget/koj6gxx6\';var x=d.getElementsByTagName(\'script\')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent(\'onload\',l);}else{w.addEventListener(\'load\',l,false);}}})()</script>\r\n    \r\n    \r\n\r\n    \r\n    \r\n\r\n    \r\n    \r\n\r\n    <script src="/static/assets/manifest.js?v=47a28ec84654"></script>\n<script src="/static/assets/vendor.js?v=39ebd7d799fc"></script>\r\n</head>\r\n<body>\r\n    \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n<div class="site-layout">\r\n        <div class="site-layout__header">\r\n            <div data-component-name="SiteHeaderContainer" style="display: flex; flex-direction: column; flex: 1 0 auto;"></div><script>var Kaggle=window.Kaggle||{};Kaggle.State=Kaggle.State||[];Kaggle.State.push({});performance && performance.mark && performance.mark("SiteHeaderContainer.componentCouldBootstrap");</script>\r\n        </div>\r\n\r\n    <div class="site-layout__main-content">\r\n        \r\n\r\n<div data-component-name="NotFound" style="display: flex; flex-direction: column; flex: 1 0 auto;"></div><script>var Kaggle=window.Kaggle||{};Kaggle.State=Kaggle.State||[];Kaggle.State.push({"imagePath":"/content/v/c4bc432a5a17/shared/img/404.png"});performance && performance.mark && performance.mark("NotFound.componentCouldBootstrap");</script>\r\n\r\n    </div>\r\n\r\n</div>\r\n\r\n\r\n\r\n<script type="text/javascript">\r\n    var Kaggle = Kaggle || {};\r\n\r\n    Kaggle.Current = {\r\n        antiForgeryToken: \'Y4SQpsFAM1wyuxcXms-1aXidCwsKbztYPtkML68RuZhrCAAyiDqUf8dGZzzjevHb-WeVYk1bdXk6ux2DVDCr-haPSfE1\',\r\n        isAnonymous: true,\r\n        isFullScreen: false,\r\n        \r\n        \r\n        \r\n        \r\n        \r\n        \r\n        \r\n        \r\n    }\r\n        Kaggle.Current.log = function(){};\r\n        Kaggle.Current.warn = function(){};\r\n    var decodeUserDisplayName = function () {\r\n        var escapedUserDisplayName = Kaggle.Current.userDisplayNameEscaped || "";\r\n        try {\r\n          var textVersion = new DOMParser().parseFromString(escapedUserDisplayName, "text/html").documentElement.textContent;\r\n          if (textVersion) {\r\n              return textVersion;\r\n          }\r\n        } catch(ex) {}\r\n        \r\n        return escapedUserDisplayName;\r\n    }\r\n    Kaggle.Current.userDisplayName = decodeUserDisplayName();\r\n</script>\r\n\r\n\r\n\r\n\r\n\r\n<script type="text/javascript">\r\n    var Kaggle = Kaggle || {};\r\n    Kaggle.PageMessages = [];\r\n</script>\r\n\r\n\r\n<script src="/content/v/5dbea6ee9ce1/shared/js/kaggle.prism.min.js"></script>\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n    <script src="/static/assets/app.js?v=4dec5729c547"></script>\r\n    \r\n        <script>\r\n            (function() {\r\n                if (\'serviceWorker\' in navigator) {\r\n                    \r\n                    navigator.serviceWorker.register("/static/assets/service-worker.js").then(function(reg) {\r\n                        \r\n                        reg.onupdatefound = function() {\r\n                            \r\n                            var installingWorker = reg.installing;\r\n                            installingWorker.onstatechange = function() {\r\n                                switch (installingWorker.state) {\r\n                                case \'installed\':\r\n                                    if (navigator.serviceWorker.controller) {\r\n                                        \r\n                                        console.log(\'New or updated content is available.\');\r\n                                    } else {\r\n                                        \r\n                                        console.log(\'Content is now available offline!\');\r\n                                    }\r\n                                    break;\r\n                                case \'redundant\':\r\n                                    console.error(\'The installing service worker became redundant.\');\r\n                                    break;\r\n                                }\r\n                            };\r\n                        };\r\n                    }).catch(function(e) {\r\n                      console.error(\'Error during service worker registration:\', e);\r\n                    });\r\n                }\r\n            })();\r\n        </script>\r\n</body>\r\n</html>\r\n'
```

The HTML response header and body content in particular seems like a weird thing to return. Seems to me that a simple error code would suffice...

**Comment by rysteboe** [comment]
I got rid of the python stack trace since that isn't terribly helpful for these cases.  There is still some extra information, including the headers because they're helpful when people report errors.  The stack trace took up most of the space, though, so it should be less annoying now.
