### ISSUE TITLE
Cannot download competition data but can list it 

### ISSUE THREAD

**Issue by flios** [Kaggle/kaggle-api#16]
Hi, 
When I tried to download the dataset of a competition, it shows an error of {"code":404,"message":"NotFound"}. But I can use the command to list the dataset. 

Thanks for any help!

`kaggle competitions files -c two-sigma-financial-modeling
name           size  creationDate
------------  -----  ------------
train.h5.zip  553MB  None

competitions download -c two-sigma-financial-modeling
Traceback (most recent call last):
  File "c:\users\flios\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\flios\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Flios\Anaconda3\Scripts\kaggle.exe\__main__.py", line 9, in <module>
  File "c:\users\flios\anaconda3\lib\site-packages\kaggle\cli.py", line 18, in main
    out = args.func(**command_args)
  File "c:\users\flios\anaconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 246, in competitionDownloadCli
    self.competitionDownloadFiles(competition, path, force, quiet)
  File "c:\users\flios\anaconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 233, in competitionDownloadFiles
    self.competitionDownloadFile(competition, file.ref, path, force, quiet)
  File "c:\users\flios\anaconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 222, in competitionDownloadFile
    response = self.process_response(self.competitions_data_download_file_with_http_info(id = competition, file_name = file, _preload_content = False))
  File "c:\users\flios\anaconda3\lib\site-packages\kaggle\api\kaggle_api.py", line 131, in competitions_data_download_file_with_http_info
    collection_formats=collection_formats)
  File "c:\users\flios\anaconda3\lib\site-packages\kaggle\api_client.py", line 318, in call_api
    _preload_content, _request_timeout)
  File "c:\users\flios\anaconda3\lib\site-packages\kaggle\api_client.py", line 149, in __call_api
    _request_timeout=_request_timeout)
  File "c:\users\flios\anaconda3\lib\site-packages\kaggle\api_client.py", line 339, in request
    headers=headers)
  File "c:\users\flios\anaconda3\lib\site-packages\kaggle\rest.py", line 235, in GET
    query_params=query_params)
  File "c:\users\flios\anaconda3\lib\site-packages\kaggle\rest.py", line 225, in request
    raise ApiException(http_resp=r)
kaggle.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'private', 'Content-Length': '33', 'Content-Type': 'application/json; charset=utf-8', 'Set-Cookie': 'TempData=.kXVFW1OTsyP0rMDHYMCVmOdw81b2Zu4hSp3Jd8BxnHAY7B/wHjgGkA6y92Y8fdXVL4qPTIJH5qft4eTEOx7+wvUo0bZUMYkCrF78EksmbQM0K73j2wRXx/A87lU5S8Wq9/sxwMhvjI0Hfkmmyaed54xtq5kCUBeppKVie5AZTAUbGayNZjnS5eWmIvTwIsrsXeB9Wu+2ScS5+S1PNlsGZ9uMzCs=; path=/; secure; HttpOnly, ARRAffinity=09c2beb4c9502b4b21d5170f783270ae843e6395502382744e0942964888b1c0;Path=/;HttpOnly;Domain=www.kaggle.com', 'X-Kaggle-MillisecondsElapsed': '95', 'X-Kaggle-RequestId': '8f9df8b37ecc25809633f9f6361bb9ba', 'X-Kaggle-ApiVersion': '1.1.0', 'X-Frame-Options': 'SAMEORIGIN', 'Date': 'Wed, 21 Mar 2018 17:18:40 GMT'})
HTTP response body: b'{"code":404,"message":"NotFound"}'`

**Comment by YSZYCF** [comment]
I also meet this issue ,I don't know why

**Comment by chunziwang** [comment]
me too.

**Comment by rysteboe** [comment]
This is likely because the competition is over.  Will look into making the error message more useful + making it clear from the list that the competition is over.

**Comment by zhoumumu** [comment]
I got the same trouble, but i'm sure it's not over.

**Comment by rysteboe** [comment]
@zhoumumu, which competition, what error, and what was the actual command you used?

**Comment by zhoumumu** [comment]
@rysteboe , 404 when download.
Sorry, I found it's an in-class competition which requires invitation for competitors. So I have no problem now, thanks!

**Comment by tingli81** [comment]
Hi, so is this data no longer available?  The competition is over but I would still like to see the data.

**Comment by rysteboe** [comment]
@tingli81 which competition?  Some competitions do not keep their data available after they close, or take it down some period of time after the competition closes.

**Comment by rysteboe** [comment]
Cleaned up the error messages here to clarify what's going on.  Please let me know if there are any additional problems.

**Comment by Jessicastrong** [comment]
[**Kaggle competitions**](https://www.techgiga.net/kaggle-competitions/) have significant differences from "typical" data science, yet they give important experience if you approach them.
