### ISSUE TITLE
Kaggle API 1.5.3 / kaggle kernels output / FileNotFoundError

### ISSUE THREAD

**Issue by ecc256** [Kaggle/kaggle-api#161]
Getting funny error on pulling output with Kaggle API 1.5.3

`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\kaggle\\1st-kernel-output\\train-sum-2019-03-06_19-09-28/events.out.tfevents.1551899368.79563aba6268'`

No clue where '/' came from in the file path:
`'C:\\kaggle\\1st-kernel-output\\train-sum-2019-03-06_19-09-28/events.out.tfevents.1551899368.79563aba6268'`
I assume, it supposed to normalize path, no?

```
kaggle>kaggle kernels output user/1st-kernel -p C:\kaggle\1st-kernel-output
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Roaming\Python\Python37\Scripts\kaggle.exe\__main__.py", line 9, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\kaggle\cli.py", line 51, in main
    out = args.func(**command_args)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\kaggle\api\kaggle_api_extended.py", line 2050, in kernels_output_cli
    self.kernels_output(kernel, path, force, quiet)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\kaggle\api\kaggle_api_extended.py", line 2021, in kernels_output
    with open(outfile, 'wb') as out:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\kaggle\\1st-kernel-output\\train-sum-2019-03-06_19-09-28/events.out.tfevents.1551899368.79563aba6268'

```

**Comment by linzzzzzz** [comment]
Came across similar issue here.. Seems like the API has a problem with output files created in the subfolders?

FileNotFoundError: [Errno 2] No such file or directory: './download/log/Pytorch-Resnet50/2
019-05-24-18-06-30.log'

**Comment by ecc256** [comment]
> Just saw this issue was fixed by this

Good to know!
Thanks!
