### ISSUE TITLE
got [SSL: CERTIFICATE_VERIFY_FAILED when use kaggle-api to download data

### ISSUE THREAD

**Issue by qclijun** [Kaggle/kaggle-api#19]
kaggle competitions download -c dogs-vs-cats -f sampleSubmission.csv

Here is the error message.
2018-04-02 09:49:59,457 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),)': /kaggle-competitions-data/kaggle/3362/sampleSubmission.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1522892976&Signature=KHdjH4gBIMthDrbBlMOueFxftrFM%2F680qg2RIdHw0vG93r9VMgZKTS2Gy8VNlKwAC5zJnivrgfd3CIPbI9UV35K4qYpWph6DmzcZzWRl9j4z7NmAq4qfx%2Fo9Oeroc%2B5ODqDlKROblTGUOvFgP7t9U9pT15QLPKynktR%2FqRcnNlsGZJCvbv%2F7S%2Fpn73fazfpYa%2Ft8fAJJlLyX4f7tWP%2BkCYwy16xIH%2BvufKNyYAzXBdKPc8ec6bZ2gNZCORR5PW44dz8YOOFY2Ns67KO%2BCTPbMCeoWxcUbXFIZZdh187gmWUOOPd%2BQGFxZMaquCeBITnL7A29SkimbCZ9GXMO76QtcA%3D%3D
2018-04-02 09:49:59,718 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),)': /kaggle-competitions-data/kaggle/3362/sampleSubmission.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1522892976&Signature=KHdjH4gBIMthDrbBlMOueFxftrFM%2F680qg2RIdHw0vG93r9VMgZKTS2Gy8VNlKwAC5zJnivrgfd3CIPbI9UV35K4qYpWph6DmzcZzWRl9j4z7NmAq4qfx%2Fo9Oeroc%2B5ODqDlKROblTGUOvFgP7t9U9pT15QLPKynktR%2FqRcnNlsGZJCvbv%2F7S%2Fpn73fazfpYa%2Ft8fAJJlLyX4f7tWP%2BkCYwy16xIH%2BvufKNyYAzXBdKPc8ec6bZ2gNZCORR5PW44dz8YOOFY2Ns67KO%2BCTPbMCeoWxcUbXFIZZdh187gmWUOOPd%2BQGFxZMaquCeBITnL7A29SkimbCZ9GXMO76QtcA%3D%3D
Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "d:\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "d:\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "d:\anaconda3\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "d:\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "d:\anaconda3\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "d:\anaconda3\lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "d:\anaconda3\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "d:\anaconda3\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Anaconda3\Scripts\kaggle.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\lib\site-packages\kaggle\cli.py", line 18, in main
    out = args.func(**command_args)
  File "d:\anaconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 122, in competitionDownloadCli
    self.competitionDownloadFile(competition, file, path, force, quiet)
  File "d:\anaconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 107, in competitionDownloadFile
    response = self.competitions_data_download_file(id = competition, file_name = file, _preload_content = False)
  File "d:\anaconda3\lib\site-packages\kaggle\api\kaggle_api.py", line 55, in competitions_data_download_file
    (data) = self.competitions_data_download_file_with_http_info(id, file_name, **kwargs)  # noqa: E501
  File "d:\anaconda3\lib\site-packages\kaggle\api\kaggle_api.py", line 131, in competitions_data_download_file_with_http_info
    collection_formats=collection_formats)
  File "d:\anaconda3\lib\site-packages\kaggle\api_client.py", line 318, in call_api
    _preload_content, _request_timeout)
  File "d:\anaconda3\lib\site-packages\kaggle\api_client.py", line 149, in __call_api
    _request_timeout=_request_timeout)
  File "d:\anaconda3\lib\site-packages\kaggle\api_client.py", line 339, in request
    headers=headers)
  File "d:\anaconda3\lib\site-packages\kaggle\rest.py", line 235, in GET
    query_params=query_params)
  File "d:\anaconda3\lib\site-packages\kaggle\rest.py", line 208, in request
    headers=headers)
  File "d:\anaconda3\lib\site-packages\urllib3\request.py", line 66, in request
    **urlopen_kw)
  File "d:\anaconda3\lib\site-packages\urllib3\request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "d:\anaconda3\lib\site-packages\urllib3\poolmanager.py", line 349, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "d:\anaconda3\lib\site-packages\urllib3\poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "d:\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "d:\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "d:\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "d:\anaconda3\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /kaggle-competitions-data/kaggle/3362/sampleSubmission.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1522892976&Signature=KHdjH4gBIMthDrbBlMOueFxftrFM%2F680qg2RIdHw0vG93r9VMgZKTS2Gy8VNlKwAC5zJnivrgfd3CIPbI9UV35K4qYpWph6DmzcZzWRl9j4z7NmAq4qfx%2Fo9Oeroc%2B5ODqDlKROblTGUOvFgP7t9U9pT15QLPKynktR%2FqRcnNlsGZJCvbv%2F7S%2Fpn73fazfpYa%2Ft8fAJJlLyX4f7tWP%2BkCYwy16xIH%2BvufKNyYAzXBdKPc8ec6bZ2gNZCORR5PW44dz8YOOFY2Ns67KO%2BCTPbMCeoWxcUbXFIZZdh187gmWUOOPd%2BQGFxZMaquCeBITnL7A29SkimbCZ9GXMO76QtcA%3D%3D (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

**Comment by kalpitsmehta** [comment]
I am seeing a similar issue. Did you find a solution?

**Comment by rysteboe** [comment]
Alternatively, try `pip install --upgrade certifi`

**Comment by rysteboe** [comment]
Did you try to install `certifi`?  Please look at the solutions within this [StackOverflow answer](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error).  If something from there works, please post back and let me know so that I can include it in a future troubleshooting guide.

**Comment by protomock** [comment]
Not sure if anyone still needs help with this but a temporary fix, if you have the pem file for your certificate, is to add the content of the pem to certfi cacert file.

```
 print "\n#####\n##### CUSTOM\n#####\n" | cat - /path/to/cert.pem >> /path/to/python/site-packages/certifi/cacert.pem
```
