### ISSUE TITLE
download of a dataset-metadata.json does not work  

### ISSUE THREAD

**Issue by m1ci** [Kaggle/kaggle-api#249]
The following command does not work
``kaggle datasets metadata username/dataset-id``

I get

```
Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/kaggle/cli.py", line 51, in main
    out = args.func(**command_args)
  File "/Library/Python/2.7/site-packages/kaggle/api/kaggle_api_extended.py", line 1048, in dataset_metadata_cli
    meta_file = self.dataset_metadata(dataset, path)
  File "/Library/Python/2.7/site-packages/kaggle/api/kaggle_api_extended.py", line 1030, in dataset_metadata
    if (result['errorMessage']):
KeyError: 'errorMessage'
```

**Comment by jorijnsmit** [comment]
Duplicate of #235.

**Comment by erdalsivri** [comment]
The duplicate bug (https://github.com/Kaggle/kaggle-api/issues/235) has been fixed so I am closing this
