### ISSUE TITLE
Error In Donloading

### ISSUE THREAD

**Issue by Gelesh** [Kaggle/kaggle-api#251]
ubuntu@ip-XXXXXXX:/buk/datacopy/data$ **~/.local/bin/kaggle competitions download -c rsna-intracranial-hemorrhage-detection**
Downloading rsna-intracranial-hemorrhage-detection.zip to /buk/datacopy/data
 54%|███████████████████████████████████████████▉                                     | 97.7G/180G [3:31:35<2:58:26, 8.26MB/s]
Traceback (most recent call last):
  File _"/home/ubuntu/.local/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py"_, line 1582, in download_file
    out.write(data)
**OSError: [Errno 5] Input/output error**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/kaggle", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kaggle/cli.py", line 51, in main
    out = args.func(**command_args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 741, in competition_download_cli
    quiet)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 708, in competition_download_files
    self.download_file(response, outfile, quiet)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 1584, in download_file
    pbar.update(len(data))
OSError: [Errno 5] Input/output error
ubuntu@ip-XXXXXXXX:/buk/datacopy/data$

**Comment by Philmod** [comment]
I couldn't reproduce this error.
