### ISSUE TITLE
kaggle --help and kaggle --version should function even without credentials

### ISSUE THREAD

**Issue by Julian** [Kaggle/kaggle-api#267]
(I'm on `kaggle-cli 1.5.6`)

Running `kaggle --help` or `kaggle --version` without a configured `kaggle.json` produces:

```
⊙  kaggle --version                                                                                                                                                                             julian@Air ●
Traceback (most recent call last):
  File "/Users/julian/.local/bin/kaggle", line 5, in <module>
    from kaggle.cli import main
  File "/Users/julian/.dotfiles/.local/share/virtualenvs/ml/lib/python3.8/site-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/Users/julian/.dotfiles/.local/share/virtualenvs/ml/lib/python3.8/site-packages/kaggle/api/kaggle_api_extended.py", line 147, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in /Users/julian/.kaggle. Or use the environment method.
/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py:265: ResourceWarning: unclosed running multiprocessing pool <multiprocessing.pool.ThreadPool state=RUN pool_size=4>
```

Instead of showing the help or version respectively.

**Comment by Monti03** [comment]
I followed [this](https://adityashrm21.github.io/Setting-Up-Kaggle/) guide and now ti works
