### ISSUE TITLE
Permission Denied : '/kaggle.json'

### ISSUE THREAD

**Issue by sanzeshstha** [Kaggle/kaggle-api#282]
I followed each step mentioned in the README.md, but I am getting a permission denied error for the kaggle.json file. I tried changing the permission to 777, even then it did not work. Could someone please assist.

$ kaggle --version
Traceback (most recent call last):
  File "/home/user/.local/bin/kaggle", line 5, in <module>
    from kaggle.cli import main
  File "/home/user/.local/lib/python3.8/site-packages/kaggle/__init__.py", line 19, in <module>
    from kaggle.api.kaggle_api_extended import KaggleApi
  File "/home/user/.local/lib/python3.8/site-packages/kaggle/api/__init__.py", line 22, in <module>
    from kaggle.api.kaggle_api_extended import KaggleApi
  File "/home/user/.local/lib/python3.8/site-packages/kaggle/api/kaggle_api_extended.py", line 68, in <module>
    class KaggleApi(KaggleApi):
  File "/home/user/.local/lib/python3.8/site-packages/kaggle/api/kaggle_api_extended.py", line 86, in KaggleApi
    os.makedirs(config_dir)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/kaggle.json'

**Comment by sowmyakavali** [comment]
I am also getting same error
`sk@sk-P243:~$ kaggle --version`
`bash: /home/sk.local/bin/kaggle: Permission denied`

**Comment by ajpen** [comment]
@sowmyakavali your issue looks different. Can you share the output of `ls -lah /home/sk.local/bin/kaggle`?

**Comment by ajpen** [comment]
@sanzeshstha Where did you put `kaggle.json'? It's supposed to be in `~/.kaggle/` from [the readme](https://github.com/Kaggle/kaggle-api#api-credentials) but your traceback tries to access it in `/`. 

Can you share the output of `which kaggle`?

**Comment by sowmyakavali** [comment]
My problem is solved 
I have uninstalled kaggle and again reinstalled it and placed that kaggle.json in right place it worked for me.
