### ISSUE TITLE
AttributeError: 'KaggleApi' object has no attribute 'competitions_data_download_files_with_http_info' ​

### ISSUE THREAD

**Issue by zabir-nabil** [Kaggle/kaggle-api#297]
I'm trying to download  a file but getting this error:

```
Could not find kaggle.json. Make sure it's located in /home/ml2/.kaggle. Or use the environment method.
Traceback (most recent call last):
  File "/home/ml2/anaconda3/envs/kag_pul/bin/kaggle", line 8, in <module>
    sys.exit(main())
  File "/home/ml2/anaconda3/envs/kag_pul/lib/python3.7/site-packages/extended/cli.py", line 34, in main
    out = args.func(**command_args)
  File "/home/ml2/anaconda3/envs/kag_pul/lib/python3.7/site-packages/extended/api/kaggle_api.py", line 763, in competition_download_cli
    quiet)
  File "/home/ml2/anaconda3/envs/kag_pul/lib/python3.7/site-packages/extended/api/kaggle_api.py", line 723, in competition_download_files
    self.competitions_data_download_files_with_http_info(
AttributeError: 'KaggleApi' object has no attribute 'competitions_data_download_files_with_http_info'
```

**Comment by fnand** [comment]
I get the same final error but a different trace: 

`  File "/home/f/Workspace/Kaggle/l5kit/l5kit_venv/bin/kaggle", line 11, in <module>
    load_entry_point('kaggle==1.5.7', 'console_scripts', 'kaggle')()
  File "/home/f/Workspace/Kaggle/l5kit/l5kit_venv/lib/python3.6/site-packages/extended/cli.py", line 34, in main
    out = args.func(**command_args)
  File "/home/f/Workspace/Kaggle/l5kit/l5kit_venv/lib/python3.6/site-packages/extended/api/kaggle_api.py", line 763, in competition_download_cli
    quiet)
  File "/home/f/Workspace/Kaggle/l5kit/l5kit_venv/lib/python3.6/site-packages/extended/api/kaggle_api.py", line 723, in competition_download_files
    self.competitions_data_download_files_with_http_info(
AttributeError: 'KaggleApi' object has no attribute 'competitions_data_download_files_with_http_info'
`

@zabir-nabil , are you sure you have created an API token? You should be able to go to "My Account" and get it with "Create New API token". There are instructions for where to place this file.

**Comment by zabir-nabil** [comment]
It seems `kaggle` command was invoking a different python version (3.6 and not 3.7). So, I did a simple hack to get it working, 

>>python3.7.5
```
import os
os.system("kaggle command")
```
Now, it works.
