### ISSUE TITLE
can't pull kernel with a 'TypeError'

### ISSUE THREAD

**Issue by soHardToHaveAName** [Kaggle/kaggle-api#331]
I successfully installed kaggle using pip on linux, and I can push kernels successfully, 

but when I input a pull request:
`kaggle kernels pull -k kaggle-test -m`

it shows an error like this:
`Traceback (most recent call last):
  File "/home/chong/anaconda3/bin/kaggle", line 8, in <module>
    sys.exit(main())
  File "/home/chong/anaconda3/lib/python3.8/site-packages/kaggle/cli.py", line 67, in main
    out = args.func(**command_args)
  File "/home/chong/anaconda3/lib/python3.8/site-packages/kaggle/api/kaggle_api_extended.py", line 2087, in kernels_pull_cli
    effective_path = self.kernels_pull(kernel,
  File "/home/chong/anaconda3/lib/python3.8/site-packages/kaggle/api/kaggle_api_extended.py", line 1970, in kernels_pull
    if '/' in kernel:
TypeError: argument of type 'NoneType' is not iterable
`

How can I solve it ?

**Comment by soHardToHaveAName** [comment]
seems like I use the wrong format of command...
using `kaggle kernels pull kaggle-test -m` works !

**Comment by yakovsushenok** [comment]
Hi. I have stumbled across the same issue and removing ```-k``` helped as well. Wondering whether this could be fixed in the [documentation](https://github.com/Kaggle/kaggle-api/wiki/kernel-Metadata)? :)
