### ISSUE TITLE
Unable to download metadata for an existing dataset

### ISSUE THREAD

**Issue by distlibs** [Kaggle/kaggle-api#367]
I tried to download metadata by using this command:
`kaggle datasets metadata -p data uciml/iris`

I got error:

```
Traceback (most recent call last):
  File "C:\Users\User\project\venv\Scripts\kaggle-script.py", line 33, in <module>
    sys.exit(load_entry_point('kaggle==1.5.12', 'console_scripts', 'kaggle')())
  File "c:\users\user\project\venv\lib\site-packages\kaggle\cli.py", line 67, in main
    out = args.func(**command_args)
  File "c:\users\user\project\venv\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 1065, in dataset_metadata_cli
    meta_file = self.dataset_metadata(dataset, path)
  File "c:\users\user\project\venv\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 1050, in dataset_metadata
    metadata = Metadata(result['info'])
  File "c:\users\user\project\venv\lib\site-packages\kaggle\models\kaggle_models_extended.py", line 96, in __init__
    self.id = parsed_info["ownerUser"] + "/" + parsed_info['datasetSlug']
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by celsofranssa** [comment]
Until now, any update on this?

**Comment by sarpu** [comment]
Bump on this issue!

**Comment by WoutervanLelyveld** [comment]
Also facing this issue!
