### ISSUE TITLE
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by jasmcaus** [Kaggle/kaggle-api#382]
The entire output is:
```bash
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.4)
Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/kaggle/cli.py", line 51, in main
    out = args.func(**command_args)
  File "/usr/local/lib/python2.7/dist-packages/kaggle/api/kaggle_api_extended.py", line 2069, in kernels_output_cli
    self.kernels_output(kernel, path, force, quiet)
  File "/usr/local/lib/python2.7/dist-packages/kaggle/api/kaggle_api_extended.py", line 2039, in kernels_output
    os.makedirs(os.path.split(outfile)[0], exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_o
```

I'm running this on Google Colab. Clearly, `/usr/loca/bin/kaggle` is defaulting to Python2.7. If I try to `pip install --upgrade kaggle`, I get:
```bash
Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2021.5.30)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.62.2)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
```
which is clearly Python3.7.

Any help? I'm not able to download any datasets onto my machine

**Comment by KalaiKumarR** [comment]
Did you resolved it?

**Comment by jasmcaus** [comment]
Nope. Still waiting for someone to clarify this.

**Comment by jplotts** [comment]
Hi @jasmcaus - from your outputs, it seems that `/usr/local/bin/kaggle` is showing version 1.5.4 which is more than 2 years old.  The `pip install --upgrade` shows the current version of 1.5.12 but it might not be installing to `/usr/local/bin/kaggle`.  You'll need to figure out where the upgraded version lives and use that one.

**Comment by KalaiKumarR** [comment]
issue solved. I uninstalled and reinstalled the Kaggle in colab. Thank you @jplotts  :)
