### ISSUE TITLE
Many syntax errors

### ISSUE THREAD

**Issue by opengeler** [Kaggle/kaggle-api#39]
I installed kaggle on windows machine with python 3.7.0b4 64 bit
pip3 install kaggle --cert"....."

getting same errors on every use of kaggle 

Traceback (most recent call last):
  File "c:\users\<username>\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\<username>\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python37\Scripts\kaggle.exe\__main__.py", line 5, in <module>
  File "c:\users\<username>\appdata\local\programs\python\python37\lib\site-packages\kaggle\__init__.py", line 18, in <module>
    from kaggle.api.kaggle_api_extended import KaggleApi
  File "c:\users\<username>\appdata\local\programs\python\python37\lib\site-packages\kaggle\api\__init__.py", line 22, in <module>
    from kaggle.api.kaggle_api_extended import KaggleApi
  File "c:\users\<username>\appdata\local\programs\python\python37\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 27, in <module>
    from ..api_client import ApiClient
  File "c:\users\<username>\appdata\local\programs\python\python37\lib\site-packages\kaggle\api_client.py", line 289
    response_type=None, auth_settings=None, async=None,
                                                                            ^
SyntaxError: invalid syntax

**Comment by rysteboe** [comment]
I was able to reproduce with 3.7b4, but not 3.6.5.  I'll make a note to check this out, but I can't prioritize problems with a beta version of Python.  Obviously there will need to be a fix in the next month or so before the official release, but I can't promise anything before then.

**Comment by rysteboe** [comment]
Just did an update that should address the 3.7 issues.  Please reopen if you're still having problems in 1.4.1+.
