### ISSUE TITLE
v1.3.9 failed to submit prediction

### ISSUE THREAD

**Issue by Hoiy** [Kaggle/kaggle-api#48]
Able to submit with the same command on v1.3.8, but failed on v1.3.9.

`kaggle competitions submit -m 'testing' -f baseline.csv`

```
Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/kaggle/cli.py", line 48, in main
    out = args.func(**command_args)
TypeError: competition_submit_cli() got an unexpected keyword argument 'file_name'
```

**Comment by rysteboe** [comment]
Fixed in `1.3.9.1`.  Sorry about that :/
