### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by achaosss** [Kaggle/kaggle-api#521]
(venv) C:\Users\Administrator\Desktop\optiver_competition>kaggle competitions download -c optiver-trading-at-the-close
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\optiver_competition\venv\Scripts\kaggle-script.py", line 33, in <module>
    sys.exit(load_entry_point('kaggle==1.5.16', 'console_scripts', 'kaggle')())
  File "C:\Users\Administrator\Desktop\optiver_competition\venv\lib\site-packages\kaggle\cli.py", line 70, in main
    out = args.func(**command_args)
  File "C:\Users\Administrator\Desktop\optiver_competition\venv\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 997, in competition_download_cli
    self.competition_download_files(competition, path, force,
  File "C:\Users\Administrator\Desktop\optiver_competition\venv\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 960, in competition_download_files
    url = response.retries.history[0].redirect_location.split('?')[0]
IndexError: tuple index out of range

**Comment by achaosss** [comment]
(venv) C:\Users\Administrator\Desktop\optiver_competition>kaggle c list
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\optiver_competition\venv\Scripts\kaggle-script.py", line 33, in <module>
    sys.exit(load_entry_point('kaggle==1.5.16', 'console_scripts', 'kaggle')())
  File "C:\Users\Administrator\Desktop\optiver_competition\venv\lib\site-packages\kaggle\cli.py", line 70, in main
    out = args.func(**command_args)
  File "C:\Users\Administrator\Desktop\optiver_competition\venv\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 713, in competitions_list_cli
    competitions = self.competitions_list(group=group,
  File "C:\Users\Administrator\Desktop\optiver_competition\venv\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 693, in competitions_list
    return [Competition(c) for c in competitions_list_result]
  File "C:\Users\Administrator\Desktop\optiver_competition\venv\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 693, in <listcomp>
    return [Competition(c) for c in competitions_list_result]
  File "C:\Users\Administrator\Desktop\optiver_competition\venv\lib\site-packages\kaggle\models\kaggle_models_extended.py", line 42, in __init__
    parsed_dict = {k: parse(v) for k, v in init_dict.items()}
AttributeError: 'str' object has no attribute 'items'

**Comment by marcimarc1** [comment]
I get the same error, for `kaggle c list` any solutions for this so far?

**Comment by Tamminhdiep97** [comment]
i encounterd this yesterday, after trying so many thing, i remembered that I create a new Token and use it on a different machine, so the machine which i am currently having the problem with probably had an outdated api token
so, i follow [this](https://github.com/Kaggle/kaggle-api?tab=readme-ov-file#api-credentials) create a new api token and add it to the machine with the error, and the error was no more
@marcimarc1 @achaosss hope this can help you

**Comment by ioneliabuzatu** [comment]
turns out @Tamminhdiep97 is right. the error was due to an outdated api

**Comment by aetherclouds** [comment]
still getting this on linux and python 3.10.12, probably because I didn't download the Kaggle CLI, but I fixed it with:
```diff
- from kaggle import api
+ from kaggle.api.kaggle_api_extended import KaggleApi
+ api = KaggleApi()
+ api.authenticate()
# use the api normally
api.competition_download_cli(...)
```

**Comment by Philmod** [comment]
The error is indeed because of a bad token. I'm updating the library to make the error clearer.

**Comment by loftusa** [comment]
@Philmod Hey, just wanted to let you know I got this error even after `pip install --upgrade kaggle`. The message was extremely confusing and I only realized it was because of the token by reading this thread.

```
base) root@alex-gpu-l4-west:/home/alex_creyonbio_com/2023-00229_diff/data/2d-image-datasets/imagenet-1k# kaggle competitions download -c imagenet-object-localization-challenge
Traceback (most recent call last):
  File "/opt/conda/bin/kaggle", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/kaggle/cli.py", line 54, in main
    out = args.func(**command_args)
  File "/opt/conda/lib/python3.10/site-packages/kaggle/api/kaggle_api_extended.py", line 1002, in competition_download_cli
    self.competition_download_files(competition, path, force,
  File "/opt/conda/lib/python3.10/site-packages/kaggle/api/kaggle_api_extended.py", line 965, in competition_download_files
    url = response.retries.history[0].redirect_location.split('?')[0]
IndexError: tuple index out of range
```

and `pip show kaggle` returns
```
Name: kaggle
Version: 1.6.12
Summary: Kaggle API
Home-page: https://github.com/Kaggle/kaggle-api
Author: Kaggle
Author-email: support@kaggle.com
License: Apache 2.0
Location: /opt/conda/lib/python3.10/site-packages
Requires: bleach, certifi, python-dateutil, python-slugify, requests, six, tqdm, urllib3
Required-by: 
```

**Comment by ANotFox** [comment]
Quick question, is there a reason as to why this error comes about? On trying twice with fresh API(s), it failed but worked on the third try. Unsure of how to reproduce this verifiably enough. Thanks for the workaround though!
