### ISSUE TITLE
Kaggle Can't download dataset using Kaggle CLI

### ISSUE THREAD

**Issue by raspipy** [Kaggle/kaggle-api#522]
i've been trying to download some datasets using the Kaggle CLI yesterday that went perfect but today it all of a sudden decided to break, i used `kaggle datasets download -d marquis03/plants-classification` And it gave me the result

 `Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\janjulius.vannieuwen\AppData\Local\Programs\Python\Python312\Scripts\kaggle.exe\__main__.py", line 7, in <module>
  File "C:\Users\janjulius.vannieuwen\AppData\Local\Programs\Python\Python312\Lib\site-packages\kaggle\cli.py", line 70, in main
    out = args.func(**command_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\janjulius.vannieuwen\AppData\Local\Programs\Python\Python312\Lib\site-packages\kaggle\api\kaggle_api_extended.py", line 1493, in dataset_download_cli
    self.dataset_download_files(dataset,
  File "C:\Users\janjulius.vannieuwen\AppData\Local\Programs\Python\Python312\Lib\site-packages\kaggle\api\kaggle_api_extended.py", line 1447, in dataset_download_files
    self.download_file(response, outfile, quiet, not force)
  File "C:\Users\janjulius.vannieuwen\AppData\Local\Programs\Python\Python312\Lib\site-packages\kaggle\api\kaggle_api_extended.py", line 1834, in download_file
    size = int(response.headers['Content-Length'])
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\janjulius.vannieuwen\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\_collections.py", line 260, in __getitem__
    val = self._container[key.lower()]
          ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'content-length'`

Does anyone know how to fix?

**Comment by Jonghyun-An** [comment]
I think it's because the token has expired or changed and is not currently a valid token.
Get a new token from your account, put it in the ~/.kaggle/kaggle.json path, and try again!

**Comment by justinrey08** [comment]
> I think it's because the token has expired or changed and is not currently a valid token. Get a new token from your account, put it in the ~/.kaggle/kaggle.json path, and try again!

Thanks for this! This definetely helped!

**Comment by Philmod** [comment]
Thanks for reporting, I have a fix for this bug that will go out today with the version `1.6.1`.
