### ISSUE TITLE
some error is happening while running the code

### ISSUE THREAD

**Issue by Karangautam870** [Kaggle/kaggle-api#578]
`!kaggle competitions download -c LANL-Earthquake-Prediction `
it gives me this error message

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/kaggle/cli.py", line 54, in main
    out = args.func(**command_args)
  File "/usr/local/lib/python3.10/dist-packages/kaggle/api/kaggle_api_extended.py", line 1002, in competition_download_cli
    self.competition_download_files(competition, path, force,
  File "/usr/local/lib/python3.10/dist-packages/kaggle/api/kaggle_api_extended.py", line 965, in competition_download_files
    url = response.retries.history[0].redirect_location.split('?')[0]
IndexError: tuple index out of range

**Comment by stevemessick** [comment]
Please run this command:
> kaggle --version

If you are not on version 1.6.12 then please update it. I just tried your example using 1.6.12 and it worked.
