### ISSUE TITLE
Support for proxy

### ISSUE THREAD

**Issue by jithurjacob** [Kaggle/kaggle-api#6]
Hi Team,

Thank you for the API. It is working for me from cloud instances but not from my work station behind corporate proxy. I have proxy details saved as environment variables in http_proxy and https_proxy. I am able to access the API using requests library. So I came to the conclusion that URL access by this library is not supporting proxy. Please take a look at the following error message.

>> kaggle competitions download -c jigsaw-toxic-comment-classification-challenge

2018-02-13 14:54:34,706 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000034965F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /api/v1/competitions/data/list/jigsaw-toxic-comment-classification-challenge
2018-02-13 14:54:35,715 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000034912E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /api/v1/competitions/data/list/jigsaw-toxic-comment-classification-challenge
2018-02-13 14:54:36,721 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003491A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /api/v1/competitions/data/list/jigsaw-toxic-comment-classification-challenge
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "c:\program files\anaconda3\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "c:\program files\anaconda3\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "c:\program files\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "c:\program files\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "c:\program files\anaconda3\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "c:\program files\anaconda3\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000000034AF588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Anaconda3\Scripts\kaggle.exe\__main__.py", line 9, in <module>
  File "c:\program files\anaconda3\lib\site-packages\kaggle\cli.py", line 18, in main
    out = args.func(**command_args)
  File "c:\program files\anaconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 120, in competitionDownloadCli
    self.competitionDownloadFiles(competition, path, force, quiet)
  File "c:\program files\anaconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 114, in competitionDownloadFiles
    files = self.competitionListFiles(competition)
  File "c:\program files\anaconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 90, in competitionListFiles
    competitionListFilesResult = self.competitions_data_list_files(id = competition)
  File "c:\program files\anaconda3\lib\site-packages\kaggle\api\kaggle_api.py", line 151, in competitions_data_list_files
    (data) = self.competitions_data_list_files_with_http_info(id, **kwargs)  # noqa: E501
  File "c:\program files\anaconda3\lib\site-packages\kaggle\api\kaggle_api.py", line 224, in competitions_data_list_files_with_http_info
    collection_formats=collection_formats)
  File "c:\program files\anaconda3\lib\site-packages\kaggle\api_client.py", line 318, in call_api
    _preload_content, _request_timeout)
  File "c:\program files\anaconda3\lib\site-packages\kaggle\api_client.py", line 149, in __call_api
    _request_timeout=_request_timeout)
  File "c:\program files\anaconda3\lib\site-packages\kaggle\api_client.py", line 339, in request
    headers=headers)
  File "c:\program files\anaconda3\lib\site-packages\kaggle\rest.py", line 235, in GET
    query_params=query_params)
  File "c:\program files\anaconda3\lib\site-packages\kaggle\rest.py", line 208, in request
    headers=headers)
  File "c:\program files\anaconda3\lib\site-packages\urllib3\request.py", line 66, in request
    **urlopen_kw)
  File "c:\program files\anaconda3\lib\site-packages\urllib3\request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "c:\program files\anaconda3\lib\site-packages\urllib3\poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "c:\program files\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "c:\program files\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "c:\program files\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "c:\program files\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\program files\anaconda3\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.kaggle.com', port=443): Max retries exceeded with url: /api/v1/competitions/data/list/jigsaw-toxic-comment-classification-challenge (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000034AF588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

**Comment by timoboz** [comment]
We're working on a V1.1 patch of the API, which most likely will contain the feature to set a proxy in the configuration file. I can't guarantee exactly when this will be out (probably in the next 2-4 weeks), so please stay tuned for updates.

**Comment by jithurjacob** [comment]
Thank you. Looking forward to the update :+1:

**Comment by timoboz** [comment]
We just added this to the new v1.1 of the API. Usage `kaggle config set -n proxy -v [server]`

**Comment by TotoTata92000** [comment]
I have the same issue so I tried to change the value of my proxy using this command line:
`kaggle config set -n proxy -v [server]` [1]
but now it says
`The specified proxy blablabla is not valid, please check your proxy settings`
so I tried to unset it using command line
`kaggle config unset -n proxy`
and it keeps saying [1]

**Comment by 28554010** [comment]
@TotoTata92000 
This problem can be solved by modifying the **kaggle.json** file under **~/.kaggle** directory.

**Comment by aashudwivedi** [comment]
@timoboz it should also respect the http_proxy and https_proxy variables.

**Comment by yuvrajkhanna** [comment]
I have the same issue can anyone tell me what exactly i have to write
i write this:
kaggle config set -n proxy -v [server]
i just replaced server with my college proxy settings now whatever i do it keeps showing this =


Traceback (most recent call last):
  File "/home/yuvraj/anaconda3/envs/tf/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 176, in _load_config
    self.api_client = ApiClient(configuration)
  File "/home/yuvraj/anaconda3/envs/tf/lib/python3.6/site-packages/kaggle/api_client.py", line 86, in __init__
    self.rest_client = rest.RESTClientObject(configuration)
  File "/home/yuvraj/anaconda3/envs/tf/lib/python3.6/site-packages/kaggle/rest.py", line 111, in __init__
    **addition_pool_args
  File "/home/yuvraj/anaconda3/envs/tf/lib/python3.6/site-packages/urllib3/poolmanager.py", line 391, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuvraj/anaconda3/envs/tf/bin/kaggle", line 7, in <module>
    from kaggle.cli import main
  File "/home/yuvraj/anaconda3/envs/tf/lib/python3.6/site-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/home/yuvraj/anaconda3/envs/tf/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 116, in authenticate
    self._load_config(config_data)
  File "/home/yuvraj/anaconda3/envs/tf/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 184, in _load_config
    ' is not valid, please check your proxy settings')
ValueError: The specified proxy [********] is not valid, please check your proxy setting

******** is just my proxy server and port

**pls can anyone help me ??**

**Comment by usernameandme** [comment]
Add this entry to ~/.kaggle/kaggle.json.
{
-----snip-----
"proxy": "http://<ip_addr>:<port>"
}

**Comment by yuvrajkhanna** [comment]
Thx for the reply yeah that was the soln it seems thanks for helping man :)

**Comment by naruto678** [comment]
open your bashrc files and add the following lines to it


export KAGGLE_USERNAME='<your username>'
export KAGGLE_KEY='<your key>'
export KAGGLE_PROXY='http://<address>:<port number>'



works perfectly
