### ISSUE TITLE
IndexError: tuple index out of range (improve error message)

### ISSUE THREAD

**Issue by karelbecerra** [Kaggle/kaggle-api#608]
Error messaging improvement's: For those of you having this issue (I do think error do not depends on competition)

**Command**: kaggle competitions download rsna-2024-lumbar-spine-degenerative-classification
**Error**: IndexError: tuple index out of range
**Cause**: Wrong or Expired API key
**Workaround**: Update your local key (~/.kaggle/kaggle.json)
**Fix**: Print out a diff message so user :-) do not spend 1/2 day finding a fix on google

`$ kaggle competitions download rsna-2024-lumbar-spine-degenerative-classification`

...

`Traceback (most recent call last):
    File "/home/karel/.local/bin/kaggle", line 8, in 
        sys.exit(main())
    File "/home/karel/.local/lib/python3.10/site-packages/kaggle/cli.py", line 54, in main
        out = args.func(**command_args)
    File "/home/karel/.local/lib/python3.10/site-packages/kaggle/api/kaggle_api_extended.py", line 1026, in competition_download_cli
        self.competition_download_files(competition, path, force,
    File "/home/karel/.local/lib/python3.10/site-packages/kaggle/api/kaggle_api_extended.py", line 989, in competition_download_files
        url = response.retries.history[0].redirect_location.split('?')[0]
IndexError: tuple index out of range
`

**After playing around I found the error is related to wrong/expired API key.**

note: You will find some very old similar bugs but are totally unrelated

**Comment by karelbecerra** [comment]
**Forgot to mention environment**:  
- Kaggle API 1.6.14
- Python 3.10.12
- Ubuntu

**How to reproduce**: edit your ~/.kaggle/kaggle.json and type some wrong key and execute **kaggle competitions download** command

**Comment by ANotFox** [comment]
Agreed, there is another issue #521 which is the same as this. I see the same error and despite the issue being closed (and having retried with a fresh token), I cannot find a workaround. 

How were you able to correct this though?

**Comment by atiyil** [comment]
is this issue still valid? the related issue https://github.com/Kaggle/kaggle-api/issues/521 seems to be closed.

**Comment by stevemessick** [comment]
I'm not sure when this was fixed, but now you get a reasonable error message.
```
$ kaggle competitions download house-prices-advanced-regression-techniques
401 Client Error: Unauthorized for url: https://www.kaggle.com/api/v1/competitions/data/download-all/house-prices-advanced-regression-techniques
```
