### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by 77QingLiu** [Kaggle/kaggle-api#61]
Hello, after submit the following code
`kaggle competitions download -c titanic -w`
I got the following error
```log
2018-06-28 09:41:18,535 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ddd8cf8>: Failed to establish a new connection: [Errno 65] No route to host',)': /kaggle-competitions-data/kaggle/3136/train.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1530409204&Signature=CXWhfr6Mwjy8V34PJ8saJhrKnhAnwKFoZYXX2YRms9LtTAtvH%2BhjqdQAfhph1rpCU5XnLH8x6kZ2zvQD1F6MZhBIGEarETADK1reuSlGJ6PKYbBspclVQVV79gE0OYUs2CWMQijNRblODNKuQA7f9pAhGyuXz1RrQxOF%2Baa2%2BsJqfXTNZVHK1VD0SH9J6xyubZ4bq6QNk54Q8sJm4DyerkRKPhLgtywo%2Bc%2BeRmBU%2FnXc0j8tjE9xc%2Fg2p3mwkY0Ez5VuJv1ncDO3%2BuFFb15%2FdXEPVywzlxp7FsONiV%2BrmRgrEFqc4HO2uLc%2FlD%2FVDUQEtehxKdXOaXziN%2FNYQjVeyw%3D%3D
2018-06-28 09:41:25,574 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ddd8d68>: Failed to establish a new connection: [Errno 65] No route to host',)': /kaggle-competitions-data/kaggle/3136/train.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1530409204&Signature=CXWhfr6Mwjy8V34PJ8saJhrKnhAnwKFoZYXX2YRms9LtTAtvH%2BhjqdQAfhph1rpCU5XnLH8x6kZ2zvQD1F6MZhBIGEarETADK1reuSlGJ6PKYbBspclVQVV79gE0OYUs2CWMQijNRblODNKuQA7f9pAhGyuXz1RrQxOF%2Baa2%2BsJqfXTNZVHK1VD0SH9J6xyubZ4bq6QNk54Q8sJm4DyerkRKPhLgtywo%2Bc%2BeRmBU%2FnXc0j8tjE9xc%2Fg2p3mwkY0Ez5VuJv1ncDO3%2BuFFb15%2FdXEPVywzlxp7FsONiV%2BrmRgrEFqc4HO2uLc%2FlD%2FVDUQEtehxKdXOaXziN%2FNYQjVeyw%3D%3D
Traceback (most recent call last):
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10ddd8e48>: Failed to establish a new connection: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liuqing/anaconda3/bin/kaggle", line 11, in <module>
    sys.exit(main())
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/kaggle/cli.py", line 48, in main
    out = args.func(**command_args)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 337, in competition_download_cli
    self.competition_download_files(competition, path, force, quiet)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 320, in competition_download_files
    quiet)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 303, in competition_download_file
    id=competition, file_name=file_name, _preload_content=False))
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/kaggle/api/kaggle_api.py", line 325, in competitions_data_download_file_with_http_info
    collection_formats=collection_formats)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/kaggle/api_client.py", line 334, in call_api
    _preload_content, _request_timeout)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/kaggle/api_client.py", line 165, in __call_api
    _request_timeout=_request_timeout)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/kaggle/api_client.py", line 355, in request
    headers=headers)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/kaggle/rest.py", line 251, in GET
    query_params=query_params)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/kaggle/rest.py", line 224, in request
    headers=headers)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/poolmanager.py", line 349, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/liuqing/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /kaggle-competitions-data/kaggle/3136/train.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1530409204&Signature=CXWhfr6Mwjy8V34PJ8saJhrKnhAnwKFoZYXX2YRms9LtTAtvH%2BhjqdQAfhph1rpCU5XnLH8x6kZ2zvQD1F6MZhBIGEarETADK1reuSlGJ6PKYbBspclVQVV79gE0OYUs2CWMQijNRblODNKuQA7f9pAhGyuXz1RrQxOF%2Baa2%2BsJqfXTNZVHK1VD0SH9J6xyubZ4bq6QNk54Q8sJm4DyerkRKPhLgtywo%2Bc%2BeRmBU%2FnXc0j8tjE9xc%2Fg2p3mwkY0Ez5VuJv1ncDO3%2BuFFb15%2FdXEPVywzlxp7FsONiV%2BrmRgrEFqc4HO2uLc%2FlD%2FVDUQEtehxKdXOaXziN%2FNYQjVeyw%3D%3D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ddd8e48>: Failed to establish a new connection: [Errno 65] No route to host',))
```

It says that `[Errno 65] No route to host'`, anyone knows how to solve this?

**Comment by 77QingLiu** [comment]
I see. It's the internet issue as this API uses Google API which has been blocked by Chinese Government. The issues fixed through connecting internet with VPN.

**Comment by dandananddada** [comment]
Love my country.

**Comment by JonXia** [comment]
> I see. It's the internet issue as this API uses Google API which has been blocked by Chinese Government. The issues fixed through connecting internet with VPN.

开了代理，但是api提交还是不行
 0%|          | 0.00/276k [00:00<?, ?B/s]2019-12-13 00:38:12,965 WARNING Retrying (Retry(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),)':
