### ISSUE TITLE
Can not submit result: kaggle1.3.12 with python3.6

### ISSUE THREAD

**Issue by thomas-young-2013** [Kaggle/kaggle-api#62]
Traceback (most recent call last):
  File "/home/daim/anaconda2/envs/python3.6/bin/kaggle", line 11, in <module>
    load_entry_point('kaggle==1.3.12', 'console_scripts', 'kaggle')()
  File "/home/daim/anaconda2/envs/python3.6/lib/python3.6/site-packages/kaggle-1.3.12-py3.6.egg/kaggle/cli.py", line 48, in main
  File "/home/daim/anaconda2/envs/python3.6/lib/python3.6/site-packages/kaggle-1.3.12-py3.6.egg/kaggle/api/kaggle_api_extended.py", line 221, in competition_submit_cli
  File "/home/daim/anaconda2/envs/python3.6/lib/python3.6/site-packages/kaggle-1.3.12-py3.6.egg/kaggle/api/kaggle_api_extended.py", line 204, in competition_submit
TypeError: string indices must be integers

**Comment by rysteboe** [comment]
There was an issue with a server deploy that broke the API.  Can you try again now?

**Comment by thomas-young-2013** [comment]
it works now, thanks!
