### ISSUE TITLE
cannot download leaderboard

### ISSUE THREAD

**Issue by BiqiangWang** [Kaggle/kaggle-api#622]
I encountered some problems when downloading leaderboard using kaggle-api.

when execute `kaggle competitions leaderboard titanic --download`, error message appears:
```
Traceback (most recent call last):
File "C:\Software\anaconda3\envs\project\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 1932, in download_file
...
remote_date = datetime.strptime(response.headers['Last-Modified'],
File "C:\Software\anaconda3\envs\project\lib\site-packages\urllib3\_collections.py", line 157, in __getitem__
val = self._container[key.lower()]
KeyError: 'last-modified'
```

**Comment by stevemessick** [comment]
@BiqiangWang Thanks for the report. We're aware of the problem. It's been fixed but not released yet.

**Comment by stevemessick** [comment]
@BiqiangWang Also, you can use`--show` to print the leaderboard, and save that to a file. I think it prints the entire leaderboard.
