### ISSUE TITLE
Error listing dataset files in cli or python

### ISSUE THREAD

**Issue by Alkem0s** [Kaggle/kaggle-api#655]
kaggle datasets files zillow/zecon

this command results in:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Alkem0s\anaconda3\Scripts\kaggle.exe\__main__.py", line 7, in <module>
  File "C:\Users\Alkem0s\anaconda3\Lib\site-packages\kaggle\cli.py", line 63, in main
    out = args.func(**command_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alkem0s\anaconda3\Lib\site-packages\kaggle\api\kaggle_api_extended.py", line 1368, in dataset_list_files_cli
    result = self.dataset_list_files(dataset, page_token, page_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alkem0s\anaconda3\Lib\site-packages\kaggle\api\kaggle_api_extended.py", line 1348, in dataset_list_files    
    return ListFilesResult(dataset_list_files_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alkem0s\anaconda3\Lib\site-packages\kaggle\models\kaggle_models_extended.py", line 169, in __init__
    files = init_dict['datasetFiles']
            ~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'datasetFiles'

**Comment by cleberecht** [comment]
We have the same problem.

**Comment by stevemessick** [comment]
This looks like a problem on the server. I've submitted a PR to fix it.
