### ISSUE TITLE
Unable to pull kernel

### ISSUE THREAD

**Issue by pdmack** [Kaggle/kaggle-api#84]
```
$ kaggle kernels list -m
ref                                              title                                         author          lastRunTime          totalVotes
-----------------------------------------------  --------------------------------------------  --------------  -------------------  ----------
pdmack/film-recommendation-engine                Film recommendation engine                    Pete MacKinnon  2018-08-24 20:32:54           0
pdmack/dog-breed-pretrained-keras-models-lb-0-3  Dog Breed - Pretrained keras models(LB 0.3)   Pete MacKinnon  2018-08-21 12:45:57           0
$ kaggle k output pdmack/film-recommendation-engine
Kernel log downloaded to /Users/pmackinn/kaggle/film-recommendation-engine.log
$ kaggle k status pdmack/film-recommendation-engine
pdmack/film-recommendation-engine has status "complete"
$ kaggle k pull pdmack/film-recommendation-engine
Traceback (most recent call last):
  File "/Users/pmackinn/.local/share/virtualenvs/kaggle-VkBqkupg/bin/kaggle", line 11, in <module>
    sys.exit(main())
  File "/Users/pmackinn/.local/share/virtualenvs/kaggle-VkBqkupg/lib/python3.6/site-packages/kaggle/cli.py", line 50, in main
    out = args.func(**command_args)
  File "/Users/pmackinn/.local/share/virtualenvs/kaggle-VkBqkupg/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 1527, in kernels_pull_cli
    kernel, path=path, metadata=metadata, quiet=False)
  File "/Users/pmackinn/.local/share/virtualenvs/kaggle-VkBqkupg/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 1479, in kernels_pull
    f.write(blob['source'])
TypeError: write() argument must be str, not None
$ kaggle -v
Kaggle API 1.4.6
$ python -V
Python 3.6.4 :: Anaconda, Inc.
```

macOS and pip-env

Any ideas? Is there some metadata in the kernel I need to look at or update?

Added a [gist](https://gist.github.com/pdmack/9e9447fcd96d70a2d4015d0694a04d47#file-kaggle-pull-error) with some of my own debug in it.

**Comment by bobsawey** [comment]
Seeing the same thing, investigating...

**Comment by bobsawey** [comment]
@pdmack just to confirm with the args we are sending blob is returning source as None. I'm peeping the api docs to see if maybe the call needs to be  updated.
{'source': None, 'language': 'python', 'kernelType': 'notebook', 'slug': 'how-to-run-kaggle-competition-on-local-computer'}

**Comment by pdmack** [comment]
I noticed server-side is 1.4.4 so maybe a swagger disconnect of some kind? I believe I tried the 1.4.4 pip to no avail though.

**Comment by rysteboe** [comment]
I think something on our backend changed.  Looking into this now.
